"""Ship the extracted walks (work/walk/m.json, f.json) into the app as a small TS module.

    python walk_to_ts.py
Writes app/src/street/body/walkData.ts. Angles in radians, lengths in body heights.
"""

from __future__ import annotations

import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "app" / "src" / "street" / "body" / "walkData.ts"


def main() -> None:
    clips = {}
    for n in ("m", "f"):
        d = json.loads((HERE / "work" / "walk" / f"{n}.json").read_text(encoding="utf-8"))
        clips[n] = {k: d[k] for k in ("phases", "period", "gait_from", "len", "heel", "toe", "stand", "walk", "contact")}
    body = json.dumps(clips, separators=(",", ":"))
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        "// Generated by pipeline/walk_to_ts.py from pipeline/work/walk/{m,f}.json: one looping stride as\n"
        "// joint angles tracked from the owner's reference walking videos (MediaPipe Pose). Joint data only;\n"
        "// nothing of the videos' pictures. Do not edit by hand.\n\n"
        "import type { WalkClip } from './skeleton';\n\n"
        f"export const WALKS: Record<'m' | 'f', WalkClip> = {body};\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
